spring.application.name=freshvita
server.port=${PORT:8080}
server.address=0.0.0.0
server.shutdown=graceful
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
spring.thymeleaf.cache=false
